# Generated by Django 2.2.1 on 2019-05-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='points',
            new_name='function_points',
        ),
        migrations.AddField(
            model_name='points',
            name='efoort',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
