# Generated by Django 2.2.1 on 2019-05-07 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0002_auto_20190507_0424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='efoort',
            new_name='effort',
        ),
    ]
