# Generated by Django 2.2.1 on 2019-05-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0003_auto_20190507_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='effort',
            field=models.IntegerField(default=0),
        ),
    ]
