# Generated by Django 2.2.1 on 2019-05-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0009_remove_loggedissue_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedissue',
            name='url',
            field=models.URLField(default='https://www.google.com/'),
        ),
    ]
