# Generated by Django 2.2.1 on 2019-05-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0010_loggedissue_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='effort',
            field=models.FloatField(default=0),
        ),
    ]
