# Generated by Django 2.2.1 on 2019-05-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0012_student_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedissue',
            name='mentor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
