# Generated by Django 2.2.1 on 2019-05-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0013_loggedissue_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='report',
            field=models.URLField(default='https://www.google.com/'),
        ),
    ]
