# Generated by Django 2.2.1 on 2019-05-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0014_student_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='SRIP19-BATCH1', max_length=100),
        ),
    ]
