# Generated by Django 2.2.1 on 2019-05-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0015_student_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='report',
            field=models.URLField(default='https://github.com/aditya3498/SRIP2019-Batch1/wiki'),
        ),
    ]
