# Generated by Django 2.2.1 on 2019-05-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0016_auto_20190510_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='handle',
            field=models.CharField(default=' ', max_length=25),
        ),
    ]
