# Generated by Django 2.2.1 on 2019-05-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0024_auto_20190512_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='handle',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
