# Generated by Django 2.2.1 on 2019-05-13 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0025_auto_20190513_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedissue',
            name='toc',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='loggedissue',
            name='mentor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
