# Generated by Django 2.2.1 on 2019-05-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0026_auto_20190513_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedissue',
            name='handle',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
