# Generated by Django 2.2.1 on 2019-05-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0028_auto_20190515_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedissue',
            name='remark',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
