# Generated by Django 2.2.1 on 2019-06-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0029_loggedissue_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedissue',
            name='css_ip',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loggedissue',
            name='html_ip',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loggedissue',
            name='js_ip',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loggedissue',
            name='remark',
            field=models.CharField(default='-', max_length=1000),
        ),
    ]
