# Generated by Django 2.2.1 on 2019-06-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0030_auto_20190601_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
